name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: anomaly51/github-actions-toolkit/.github/workflows/fluxcd-image-release.yml@v11
    with:
      app-name: Shisha Guide Backend
      runner: anomaly51-runner
      concurrency-group: shisha-backend
      registry: harbor.api-api-api.com
      registry-resolve-host: traefik.kube-system.svc.cluster.local
      image-project: shisha
      image-name: backend
      app-url: https://shisha-guid-api.api-api-api.com
      health-url: https://shisha-guid-api.api-api-api.com/health
    secrets:
      registry_username: ${{ secrets.HARBOR_USERNAME }}
      registry_password: ${{ secrets.HARBOR_PASSWORD }}
      telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
